# -*- coding: utf-8 -*-
from exception import PyLibsException


class CallTrackingException(PyLibsException):
    pass
